### PR TITLE
Dsp 926 transport support for cassandra server including ssl

### PR DESCRIPTION
**Pull request by alexliu68**

### CODE REVIEW

**Comment by pkolaczk** [comment]
Before +1, we have to discuss how we do client transport factories. Do we keep using TTransportFactory and workaround somehow the problem of abstracting out the opening / throwing exceptions or do we extend that factory somehow. If we go with extending, that would need modifying some cassandra code, so hold on with cassandra patches for a while.

**Comment by pkolaczk** [comment]
TClientFactory name suggests that this factory creates a client, i.e. Cassandra.IFace, not a TSocket. Anyway, what does it abstract? Creating a socket? 

Maybe I wasn't clear enough, so I try using different words:

There are already two similar factories for obtaining transport in Cassandra code: TTransportFactory and ITransportFactory. ITransportFactory is already used by some clients, e.g. in CFRR and CFRW (used by pig and hive) as well as in our JDBC driver and there are two implementations: TSecureTransportFactory (in DSE) and TFramedTransportFactory (in Cassandra). ITransportFactory was intended to provide an abstract way to get transports for _clients_. It provides method for opening transport, because opening transport can be different depending on the transport - e.g. TSecureTransportFactory needs to open it in the context of different user. So ITransportFactory is probably what you want to use also for obtaining SSL transport. Additionally ITransportFactory allows for throwing e.g. LoginException, which TTransportFactory doesn't, and determinnig LoginExceptions from other failures would be at least ugly (wrapping and unwrapping in RuntimeException). It is also placed in cassandra-thrift so external clients don't need a full cassandra on their classpath (thanks to Sam).

So the general idea is to have _one_ single transport factory interface used by all the clients. 

As you can see, the name of ITransportFactory is little unfortunate. So - rename it to e.g. IClientTransportFactory, eventually let it extend TTransportFactory (it isn't doing it now, but only do that if really needed) and then make use of it for your SSLTransport. Instead of extending, consider using TTransportFactory or direct TSockets under-the-hood in you implementation.

If ITransportFactory doesn't satisfy you somehow, ping me, then we think how to fix it. But we want to have all client transports configurable in the same way and using the same common transport factory interface - so if we ever need to add a new transport to all clients, we can do it by adding one class, not doing it for every client separately.

**Comment by alexliu68** [comment]
I am not sure about whether keep TTransportFactory or extending it.  DSP-1089 is created for it

**Comment by pkolaczk** [comment]
+1

**Comment by sbtourist** [comment]
I'm still unable to run Cassandra from this branch, with client SSL enabled.

**Pull request closed without merging**
