### PR TITLE
CASSANDRA-4295 (cached authorize() results)

### PR DESCRIPTION
**Pull request by iamaleksey**

### CODE REVIEW

**Comment by sdelmas** [comment]
Is the permission cache gonna be invalidated when the user's permissions are changed? Or do we expect that the current session continues as is, and a logout/login is required?

**Comment by iamaleksey** [comment]
No, invalidation is impossible in a distributed environment - read the full discussion in the comments in ASF jira 4295. Here we do time-based expiration with configurable ttl.

**Comment by sdelmas** [comment]
Ok, thx +1 then

**Comment by alexliu68** [comment]
potentially we could make cache per user. but it may not be security.

+1 for per session approach.

**Pull request merged**
